services:
  ua_api:
    build: ./backend
    container_name: useragent_api
    ports:
      - "9001:3001"
    restart: always

  ua_frontend:
    build: ./frontend
    container_name: useragent_frontend
    ports:
      - "9000:4173"
    restart: always
